# Generated by Django 5.2.11 on 2026-02-12 18:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constructor_id', models.CharField(help_text='External API constructor ID', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['constructor_id'], name='core_constr_constru_4d90a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(help_text='External API driver ID', max_length=100, unique=True)),
                ('number', models.IntegerField(blank=True, help_text='Permanent driver number', null=True)),
                ('code', models.CharField(blank=True, help_text='Three-letter driver code', max_length=3)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['driver_id'], name='core_driver_driver__20a3d2_idx'), models.Index(fields=['code'], name='core_driver_code_7cd62c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.CharField(help_text='External API race ID', max_length=100, unique=True)),
                ('season', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950)])),
                ('round', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('race_name', models.CharField(max_length=255)),
                ('circuit_id', models.CharField(max_length=100)),
                ('circuit_name', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-season', 'round'],
                'indexes': [models.Index(fields=['race_id'], name='core_race_race_id_be19fe_idx'), models.Index(fields=['season', 'round'], name='core_race_season_002d36_idx'), models.Index(fields=['date'], name='core_race_date_3f7ebe_idx')],
                'unique_together': {('season', 'round')},
            },
        ),
        migrations.CreateModel(
            name='ChampionshipStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950)])),
                ('standing_type', models.CharField(choices=[('driver', 'Driver Championship'), ('constructor', 'Constructor Championship')], max_length=20)),
                ('round', models.IntegerField(help_text='0 means season total', validators=[django.core.validators.MinValueValidator(0)])),
                ('position', models.IntegerField()),
                ('points', models.FloatField()),
                ('wins', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('constructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='core.constructor')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='core.driver')),
            ],
            options={
                'ordering': ['season', '-round', 'standing_type', 'position'],
                'indexes': [models.Index(fields=['season', 'standing_type', 'round'], name='core_champi_season_08100a_idx'), models.Index(fields=['driver', 'season'], name='core_champi_driver__ee5e3b_idx'), models.Index(fields=['constructor', 'season'], name='core_champi_constru_590941_idx')],
            },
        ),
        migrations.CreateModel(
            name='Lap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('position', models.IntegerField(help_text='Position at the end of this lap')),
                ('lap_time', models.CharField(help_text='Lap time in format mm:ss.SSS', max_length=20)),
                ('lap_time_milliseconds', models.IntegerField(blank=True, help_text='Lap time in milliseconds for easier comparison', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='core.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='core.race')),
            ],
            options={
                'ordering': ['race', 'lap_number', 'position'],
                'indexes': [models.Index(fields=['race', 'lap_number'], name='core_lap_race_id_8f61a1_idx'), models.Index(fields=['driver', 'race'], name='core_lap_driver__ccf4b1_idx'), models.Index(fields=['lap_time_milliseconds'], name='core_lap_lap_tim_1b49c2_idx')],
                'unique_together': {('race', 'driver', 'lap_number')},
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_position', models.IntegerField(help_text='Starting grid position')),
                ('final_position', models.IntegerField(blank=True, help_text='Final race position', null=True)),
                ('position_text', models.CharField(help_text='Position text (handles DNF, DSQ, etc)', max_length=10)),
                ('points', models.FloatField(default=0.0)),
                ('laps_completed', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('finished', 'Finished'), ('dnf', 'Did Not Finish'), ('dsq', 'Disqualified'), ('dns', 'Did Not Start'), ('retired', 'Retired')], default='finished', max_length=20)),
                ('fastest_lap', models.IntegerField(blank=True, help_text='Lap number of fastest lap', null=True)),
                ('fastest_lap_time', models.CharField(blank=True, max_length=20, null=True)),
                ('fastest_lap_speed', models.FloatField(blank=True, help_text='Speed in km/h', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.constructor')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.race')),
            ],
            options={
                'ordering': ['race', 'final_position'],
                'indexes': [models.Index(fields=['race', 'final_position'], name='core_result_race_id_a1caf0_idx'), models.Index(fields=['driver', 'race'], name='core_result_driver__0c4899_idx'), models.Index(fields=['points'], name='core_result_points_7b9553_idx')],
                'unique_together': {('race', 'driver')},
            },
        ),
    ]
