# Generated by Django 5.2.11 on 2026-02-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructor',
            name='car_image_url',
            field=models.URLField(blank=True, help_text='URL to car image', null=True),
        ),
        migrations.AddField(
            model_name='constructor',
            name='car_model',
            field=models.CharField(blank=True, help_text='Car model name for the season', max_length=50, null=True),
        ),
    ]
