# Generated by Django 5.2.11 on 2026-02-12 20:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_constructor_team_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1950)])),
                ('is_active', models.BooleanField(default=False, help_text='Currently active/selected season')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.AlterField(
            model_name='constructor',
            name='car_model',
            field=models.CharField(blank=True, help_text='Car model name for current season', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='DriverSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers_in_season', to='core.constructor')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_data', to='core.driver')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_data', to='core.season')),
            ],
            options={
                'ordering': ['-season__year', 'driver__last_name'],
                'indexes': [models.Index(fields=['season', 'constructor'], name='core_driver_season__105c87_idx'), models.Index(fields=['driver', 'season'], name='core_driver_driver__e7a2b6_idx')],
                'unique_together': {('driver', 'season', 'constructor')},
            },
        ),
        migrations.CreateModel(
            name='ConstructorSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(blank=True, help_text='Car model name for the season', max_length=50, null=True)),
                ('car_image_url', models.URLField(blank=True, help_text='URL to car image', null=True)),
                ('team_color', models.CharField(blank=True, help_text='Team primary color in hex format', max_length=7, null=True)),
                ('team_color_secondary', models.CharField(blank=True, help_text='Team secondary color', max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_data', to='core.constructor')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constructor_data', to='core.season')),
            ],
            options={
                'ordering': ['-season__year', 'constructor__name'],
                'indexes': [models.Index(fields=['season', 'constructor'], name='core_constr_season__99baa4_idx')],
                'unique_together': {('constructor', 'season')},
            },
        ),
    ]
