# Generated by Django 5.2.11 on 2026-02-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_constructor_car_image_url_constructor_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructor',
            name='team_color',
            field=models.CharField(blank=True, help_text='Team primary color in hex format', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='constructor',
            name='team_color_secondary',
            field=models.CharField(blank=True, help_text='Team secondary color', max_length=7, null=True),
        ),
    ]
