# Generated by Django 5.2.11 on 2026-02-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_race_weekend_data'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='qualifying',
            new_name='core_qualif_race_id_82e934_idx',
            old_name='core_qualif_race_id_pos_idx',
        ),
        migrations.RenameIndex(
            model_name='sprint',
            new_name='core_sprint_race_id_f46af0_idx',
            old_name='core_sprint_race_id_pos_idx',
        ),
        migrations.AddIndex(
            model_name='qualifying',
            index=models.Index(fields=['driver', 'race'], name='core_qualif_driver__55591b_idx'),
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['driver', 'race'], name='core_sprint_driver__08a2e5_idx'),
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['points'], name='core_sprint_points_85984f_idx'),
        ),
    ]
