# Generated by Django 5.2.11 on 2026-03-09 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_core_qualif_race_id_pos_idx_core_qualif_race_id_82e934_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreePractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(choices=[('FP1', 'Free Practice 1'), ('FP2', 'Free Practice 2'), ('FP3', 'Free Practice 3')], help_text='Practice session (FP1/FP2/FP3)', max_length=3)),
                ('position', models.IntegerField(help_text='Session classification position')),
                ('best_lap_time', models.CharField(blank=True, help_text='Best lap time in format m:ss.SSS', max_length=20, null=True)),
                ('laps', models.IntegerField(default=0, help_text='Number of laps completed in the session')),
                ('gap_to_leader', models.CharField(blank=True, help_text='Gap to P1 (e.g. +0.345)', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_results', to='core.constructor')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_results', to='core.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_results', to='core.race')),
            ],
            options={
                'ordering': ['race', 'session', 'position'],
                'indexes': [models.Index(fields=['race', 'session', 'position'], name='core_freepr_race_id_ab3039_idx'), models.Index(fields=['driver', 'race'], name='core_freepr_driver__cf5870_idx')],
                'unique_together': {('race', 'driver', 'session')},
            },
        ),
    ]
