# Generated by Django 5.2.11 on 2026-05-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_free_practice_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructor',
            name='car_image_url',
            field=models.URLField(blank=True, help_text='URL to car image', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='constructorseason',
            name='car_image_url',
            field=models.URLField(blank=True, help_text='URL to car image', max_length=500, null=True),
        ),
    ]
